services:

  {{ cookiecutter.class_prefix }}SystemRM:
    container_name: {{ cookiecutter.class_prefix }}SystemRM
    image: {{ cookiecutter.prefix }}_interface
    ports:
      - 127.0.0.1:5002:5002
    build:
      context: ..
      dockerfile: {{ cookiecutter.prefix }}_rm_interface/Dockerfile
    env_file:
      - ../environment.env
